### PR TITLE
chore: remove setuptools dependency (bump pyevm to 0.9.0-beta.1)

### PR DESCRIPTION
**Pull request by wakamex**
### What I did

fixes shadow dependency on setuptools, because py-evm < 0.9 uses pkg_resources to set its version without listing setuptools as a dependency. 
working toward fully removed dependence on setuptools in ape, tracking PR here: https://github.com/ApeWorX/ape/pull/2003
might break something since I don't know why the cap was there in the first place, but the tests pass

### How I did it

remove capped dependency, and set minimum to first version of py-evm that uses importlib instead of pkg_resources (0.9)

### How to verify it

```
pytest -m "not fuzzing" -n 0 -s --cov
==== 34 passed in 3.04s ===
```

### Checklist

- [x] Passes all linting checks (pre-commit and CI jobs)
- [x] New test cases have been added and are passing
- [x] Documentation has been updated
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by wakamex** [comment]
aw feck, trying to install ape results in dependency hell

```
uv pip install -e .       
   Built file:///code/newape                                                                                          Built 1 editable in 771ms
 Updated https://github.com/wakamex/evm-trace.git (4dcf86d)                                                             × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of web3[tester] are available:
          web3[tester]<=6.16.0
          web3[tester]==6.17.0
          web3[tester]>=7
      and web3[tester]==6.16.0 depends on eth-tester[py-evm]==0.9.1b2, we can conclude that
      web3[tester]>=6.16.0,<6.17.0 depends on eth-tester[py-evm]==0.9.1b2. (1)

      Because eth-tester[py-evm]==0.9.1b2 depends on py-evm==0.7.0a4 and evm-trace==0.1.dev141+g4dcf86d depends
      on py-evm>=0.9, we can conclude that eth-tester[py-evm]==0.9.1b2 and evm-trace==0.1.dev141+g4dcf86d are
      incompatible.
      And because we know from (1) that web3[tester]>=6.16.0,<6.17.0 depends on eth-tester[py-evm]==0.9.1b2, we can
      conclude that evm-trace==0.1.dev141+g4dcf86d and any of:
          web3[tester]>=6.16.0,<6.17.0
          web3[tester]>6.17.0,<7
       are incompatible.
      And because only evm-trace==0.1.dev141+g4dcf86d is available, we can conclude that all versions of evm-trace
      and any of:
          web3[tester]>=6.16.0,<6.17.0
          web3[tester]>6.17.0,<7
       are incompatible. (2)

      Because eth-tester==0.11.0b1 depends on eth-account>=0.11.2 and only the following versions of eth-tester
      are available:
          eth-tester<=0.11.0b1
          eth-tester>=0.12.0b1
      we can conclude that eth-tester>=0.11.0b1 depends on eth-account>=0.11.2.
      And because web3[tester]==6.17.0 depends on eth-tester>=0.11.0b1, we can conclude that web3[tester]==6.17.0
      depends on eth-account>=0.11.2.
      And because we know from (2) that all versions of evm-trace and any of:
          web3[tester]>=6.16.0,<6.17.0
          web3[tester]>6.17.0,<7
       are incompatible, we can conclude that all versions of evm-trace, eth-account<0.11.2, web3[tester]>=6.16.0,<7
      are incompatible.
      And because eth-ape==0.7.15.dev5+gdbe67d70.d20240415 depends on eth-account>=0.10.0,<0.11 and
      eth-ape==0.7.15.dev5+gdbe67d70.d20240415 depends on web3[tester]>=6.16.0,<7, we can conclude that all versions
      of evm-trace and eth-ape==0.7.15.dev5+gdbe67d70.d20240415 are incompatible.
      And because eth-ape==0.7.15.dev5+gdbe67d70.d20240415 depends on evm-trace and you require
      eth-ape==0.7.15.dev5+gdbe67d70.d20240415, we can conclude that the requirements are unsatisfiable.

      hint: evm-trace was requested with a pre-release marker (e.g., any of:
          evm-trace<0.1.dev141+g4dcf86d
          evm-trace>0.1.dev141+g4dcf86d
      ), but pre-releases weren't enabled (try: `--prerelease=allow`)

      hint: eth-tester was requested with a pre-release marker (e.g., eth-tester>0.11.0b1,<0.12.0b1), but
      pre-releases weren't enabled (try: `--prerelease=allow`)
```

**Review by antazoey — APPROVED** [review]

**Comment by antazoey** [comment]
actually have to do this first @NotPeopling2day https://github.com/ApeWorX/evm-trace/pull/63

**Comment by wakamex** [comment]
isn't this identical to #63?

**Comment by antazoey** [comment]
> isn't this identical to #63? (just with a different version)

one we could do, one has to wait.

**Comment by antazoey** [comment]
oh web3.py released again, so we could have done this. lol. sorry!

**Review by antazoey — APPROVED** [review]

**Pull request merged**
